name: revised-format
on:
  push: 
    branches:
      - revised-format
  workflow_dispatch:
    branches:
      - revised-format

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          ref: revised-format

      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy
        run: |
          mkdocs gh-deploy

      - name: pandoc
        uses: MatthiasValvekens/pandoc-iso@master
        with:
          md-in: spec.md
          docx-out: docs/spec.docx

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-toip-draft
          path: docs/spec.docx